# Used with eksctl version > 1.31
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CHANGE_CLUSTER_NAME
  region: CHANGE_REGION

nodeGroups:
  - name: hub
    instanceType: m5.large
    minSize: 1
    maxSize: 2
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    labels:
      node-role.kubernetes.io/role: hub
      hub.jupyter.org/node-purpose: core
    ami: auto
    amiFamily: AmazonLinux2
    ssh:
      publicKeyPath: CHANGE_PUBLICKEY
    iam:
      withAddonPolicies:
          autoScaler: true
          efs: true
  - name: user-notebook
    instanceType: m5.2xlarge
    minSize: 0
    maxSize: 100
    desiredCapacity: 0
    volumeSize: 100
    volumeType: gp2
    labels:
      node-role.kubernetes.io/role: user-notebook
      hub.jupyter.org/node-purpose: user
    taints:
      hub.jupyter.org/dedicated: 'user:NoSchedule'
    ami: auto
    amiFamily: AmazonLinux2
    ssh:
      publicKeyPath: CHANGE_PUBLICKEY
    iam:
      withAddonPolicies:
          autoScaler: true
          efs: true
  - name: dask-worker
    minSize: 0
    maxSize: 100
    instancesDistribution:
      instanceTypes: ["r5.2xlarge", "r5a.2xlarge", "r4.2xlarge"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 10
      spotInstancePools: 3
    volumeSize: 100
    volumeType: gp2
    labels:
      node-role.kubernetes.io/role: dask-worker
      k8s.dask.org/node-purpose: worker
    taints:
      k8s.dask.org/dedicated: 'worker:NoSchedule'
    desiredCapacity: 0
    ami: auto
    amiFamily: AmazonLinux2
    ssh:
      publicKeyPath: CHANGE_PUBLICKEY
    iam:
      withAddonPolicies:
          autoScaler: true
          efs: true
